### PR TITLE
fix food-picker

### PR DESCRIPTION
**Pull request by iida-hayato**

### CODE REVIEW

**Comment by Oceanel51** [comment]
Hi! Why you close this?

**Comment by Oceanel51** [comment]
@iida-hayato, maybe you want to be a collaborator? It's easy to make commits.

I think, easy way to make food-picker not cheaty - when food-picker pick, some health of entity reduce. The same applies to scissors.

Regarding balance:
max_health of Trees now = 150,
One fertile tree give - when use scissors - 20 fruits = 150 / 20 = 7.5 HP damage to tree entity
One fertile tree give - when use food-picker - 40-60 fruits = 150 / 60 ... 40 = 2.5 ... 3.75 HP damage to tree entity.

**Comment by iida-hayato** [comment]
> Hi! Why you close this?


Sorry, I found this fix cause a 'sync error' in multiplayer game.
I'm fixing now :)

**Comment by iida-hayato** [comment]
>cause a 'sync error' in multiplayer game.
 
because of 'random' tree choice

**Comment by iida-hayato** [comment]
> maybe you want to be a collaborator? It's easy to make commits.

Yes, that seems to be faster. 👍 

> Regarding balance:
max_health of Trees now = 150,
One fertile tree give - when use scissors - 20 fruits = 150 / 20 = 7.5 HP damage to tree entity
One fertile tree give - when use food-picker - 40-60 fruits = 150 / 60 ... 40 = 2.5 ... 3.75 HP damage to tree entity.

seems good idea. I will try to implement it in this PR

**Comment by Oceanel51** [comment]
> > maybe you want to be a collaborator? It's easy to make commits.
> 
> Yes, that seems to be faster. 
> 
Done
> > Regarding balance:
> > max_health of Trees now = 150,
> > One fertile tree give - when use scissors - 20 fruits = 150 / 20 = 7.5 HP damage to tree entity
> > One fertile tree give - when use food-picker - 40-60 fruits = 150 / 60 ... 40 = 2.5 ... 3.75 HP damage to tree entity.
> 
> seems good idea. I will try to implement it in this PR

And when there are no HP left in the tree entity, then it is destroyed and the Player receives wood and raw-straw (Plant mesh). Also, a little raw-straw can be obtained by using a food picker, because it is a rough mechanism, unlike human hands.
Also a burner-food-picker may be more substandard than an electric one. For example, to collect 20-40 fruits and about 120 raw-straw from a tree, as opposed to electric - 40-60 fruits and 60 raw-straw.
The amount of fruit need tie to "prototypes\trees\trees.lua" table from line 2 - row 17, raw-straw - row 11.

**Comment by iida-hayato** [comment]
> Done

thx!

**Comment by iida-hayato** [comment]
@Oceanel51  I can't see the merge button yet, can you check the settings?

**Comment by Oceanel51** [comment]
You must accept the invitation first https://github.com/Oceanel51/FoodIndustry/invitations

**Comment by iida-hayato** [comment]
thx! I got it!

**Comment by iida-hayato** [comment]
i finished work!
- fix desync bugs
- change to tree damaged approach
- balance of resources that can be collected is provisional.
  - there is less problem to play

**Pull request merged**
