### PR TITLE
Nutrient bonus

### PR DESCRIPTION
**Pull request by iida-hayato**
# related
#23 

# tasks
- [x] provisional GUI for active effect
- [x] refactoring Effect code
- [x] add Nutrient valance effect

# feature
- show important active effects in GUI 
factorio foodindustory 2019-09-16 123115

- Nutrient bonus
https://github.com/Oceanel51/FoodIndustry/pull/25/files#diff-161ab365d3ff78bc8b05c0f0981e0d13R774-R823

player vmcf all above 10 then get 10% speed bonus
if above 20 then 20% speed bonus
and its continue to 100 for 100% speed bonus

other hands
if player get vitamin above 10 then get 10% mining bonus (it's independent of other nutrients)
as well to 100% mining bonus

And similarly
more mineral get crafting bonus
more protein and fat get health_buffer bonus.

## Summary
If player get all 100% Nutrients, then 100% speed & 100% crafting & 100% mining & 200% health buff bonus :) 

# fix
- energy usage now stacking
- initialize global values when player died (for multiplay)

### CODE REVIEW

**Comment by Oceanel51** [comment]
Cool! Good work!
Pay attention to this:
- in **prototypes\functions\fi-GUI.lua** there is **function figui.add_effect_to_gui(index, player, effect_name)** whereit was supposed to add effects to the GUI
64933045-07367880-d87e-11e9-92fb-fc888630643d-2
- icons are in \graphics\icons\effects\, for tests
unknown_blue.png
unknown_gray.png
unknown_green.png
unknown_red.png
later we will do according to the effects.
- icon scales and text sizes should not be large, maybe even smaller than I showed, so as not to interfere with the Player
- tooltips should be static, since they don’t normally change dynamically
- as a goal, I want the tips to contain the value of the bonus, and from which this bonus are, and in the form of a column, for example
Effects bonus tooltip

**Comment by iida-hayato** [comment]
@Oceanel51  thx for comment. I understand your idea, it's cool.

I have a suggestion.
Adjustment of the GUI take a lot time (I'm not yet familiar with dynamic timers and hover-overs)
, and with the current implementation it works as a minimum as a game effect.

 So how about merge this PR and working about GUI on another branch?

**Comment by Oceanel51** [comment]
> Adjustment of the GUI take a lot time (I'm not yet familiar with dynamic timers and hover-overs)
> , and with the current implementation it works as a minimum as a game effect.

Nothing complicated there. For example for Speed effect the total timer is stored in row 3 in
global.effects[index]["speed"] = {false, 0, 0, 0, {}}
every tick, it decreases by some value, and every second its value needs to be extracted and updated on GUI. You can see how it was done by Villfuk02 in old versions, for 0.16.
https://github.com/Oceanel51/FoodIndustry/blob/09fb5cb25f6f21c122ec743398ba9fcbb9bef4ee/control.lua#L777

> So how about merge this PR and working about GUI on another branch?

I will merge it. Ok, GUI we will finalize over time.

**Comment by Oceanel51** [comment]
Check this too
https://docs.google.com/spreadsheets/d/1oqpEAtimP2Bobl_C1h1KVcWVMHzwyn_IpFDsTrE2uJc/edit?usp=sharing especially "Effects" sheet

**Comment by iida-hayato** [comment]
Thank you for the polite explanation.
  I'll start working about GUI after solving a few more playing issues. 👍

**Pull request merged**
