### PR TITLE
adjust to 0.18.17

### PR DESCRIPTION
**Pull request by iida-hayato**
#37 
- version up
- fix crush bugs caused by sound

### CODE REVIEW

**Comment by iida-hayato** [comment]
@Oceanel51  finished multiplay test in 0.18.17

**Comment by iida-hayato** [comment]
@Oceanel51  If you're busy, if you give me mod portal permissions, I'll release it instead

**Comment by Oceanel51** [comment]
I released. Need to test. Have a good game.

**Comment by iida-hayato** [comment]
thanks! 👍

**Pull request merged**
